<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:tns="http://ws.apache.org/axis2" targetNamespace="http://ws.apache.org/axis2Artifacts" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <partnerLinkType name="StudentenServicePortTypePLT" xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <role name="StudentenServicePortTypeRole" portType="tns:StudentenServicePortType"/>
  </partnerLinkType>
  <import location="StudentenService.wsdl" namespace="http://ws.apache.org/axis2"/>
</definitions>
